import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'unit',
          environment: 'node',
          include: ['tests/unit/**/*.test.ts'],
        },
      },
      {
        test: {
          name: 'integration',
          environment: 'node',
          include: ['tests/integration/**/*.test.ts'],
          exclude: [
            'tests/integration/delivery/formats.test.ts',
            'tests/integration/delivery/reprocess.test.ts',
            'tests/integration/media/metadata.test.ts',
            'tests/integration/media/metadata-http.test.ts',
            'tests/integration/media/process.test.ts',
            'tests/integration/media/reprocess.test.ts',
            'tests/integration/media/reprocess-http.test.ts',
            'tests/integration/media/watermark.test.ts',
            'tests/integration/media/preview.test.ts',
            'tests/integration/media/preview-http.test.ts',
            'tests/integration/media/formats.test.ts',
            'tests/integration/media/format-recovery.test.ts',
            'tests/integration/upload/formats.test.ts',
            'tests/integration/media/file-formats.test.ts',
            'tests/integration/media/svg.test.ts',
            'tests/integration/media/watermark-validation.test.ts',
            'tests/integration/media/watermark-assets.test.ts',
            'tests/integration/media/watermark-http.test.ts',
            'tests/integration/media/watermark-runtime.test.ts',
            'tests/integration/media/formats-tools.test.ts',
            'tests/integration/media/recovery-tools.test.ts',
            'tests/integration/media/delete-tools.test.ts',
            'tests/integration/upload/local.test.ts',
            'tests/integration/upload/local-http.test.ts',
          ],
        },
      },
      {
        test: {
          name: 'media-tools',
          environment: 'node',
          include: [
            'tests/integration/delivery/formats.test.ts',
            'tests/integration/delivery/reprocess.test.ts',
            'tests/integration/media/metadata.test.ts',
            'tests/integration/media/metadata-http.test.ts',
            'tests/integration/media/process.test.ts',
            'tests/integration/media/reprocess.test.ts',
            'tests/integration/media/reprocess-http.test.ts',
            'tests/integration/media/watermark.test.ts',
            'tests/integration/media/preview.test.ts',
            'tests/integration/media/preview-http.test.ts',
            'tests/integration/media/formats.test.ts',
            'tests/integration/media/format-recovery.test.ts',
            'tests/integration/upload/formats.test.ts',
            'tests/integration/media/file-formats.test.ts',
            'tests/integration/media/svg.test.ts',
            'tests/integration/media/watermark-validation.test.ts',
            'tests/integration/media/watermark-assets.test.ts',
            'tests/integration/media/watermark-http.test.ts',
            'tests/integration/media/watermark-runtime.test.ts',
            'tests/integration/media/formats-tools.test.ts',
            'tests/integration/media/recovery-tools.test.ts',
            'tests/integration/media/delete-tools.test.ts',
            'tests/integration/upload/local.test.ts',
            'tests/integration/upload/local-http.test.ts',
          ],
        },
      },
    ],
  },
});
